language: r
r:
  - release
  - devel
#r_github_packages:
#  - kevinushey/sourcetools

os:
  - linux
  - windows
  - osx

matrix:
  include:
    - os: linux
      dist: trusty
      cache: packages
      sudo: required
    - os: osx
      osx_image: xcode7.2
      cache: packages
    - os: windows
      cache: packages
