language: r
cache: packages
r:
  - oldrel
  - release
  - devel
warnings_are_errors: true
sudo: required
dist: trusty

after_success:
  - Rscript -e 'pkgdown::build_site()'

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_PAT
  keep-history: true
  local-dir: docs
  on:
    branch: master
